# Generated by Django 5.0 on 2025-06-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_loading_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='parking_coords',
            new_name='parking1_description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='parking_description',
            new_name='parking2_description',
        ),
        migrations.AddField(
            model_name='location',
            name='parking1_coords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parking2_coords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parking3_coords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parking3_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parking4_coords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parking4_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parking5_coords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parking5_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
