# Generated by Django 5.0 on 2025-06-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_rename_parking_coords_location_parking1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='night_unloading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='night_unloading_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
