# Generated by Django 5.0 on 2025-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_night_unloading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='entry_coords',
            field=models.CharField(max_length=50, verbose_name='Współrzędne bramy wjazdowej'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loading_coords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Współrzędne załadunku/rozładunku'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loading_description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis załadunku/rozładunku'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='location',
            name='night_unloading',
            field=models.BooleanField(default=False, verbose_name='Rozładunek nocny'),
        ),
        migrations.AlterField(
            model_name='location',
            name='night_unloading_description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis rozładunku nocnego'),
        ),
        migrations.AlterField(
            model_name='location',
            name='office_coords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Współrzędne biura'),
        ),
        migrations.AlterField(
            model_name='location',
            name='office_description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis biura'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking1_coords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Współrzędne parkingu 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking1_description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis parkingu 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking2_coords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Współrzędne parkingu 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking2_description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis parkingu 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking3_coords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Współrzędne parkingu 3'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking3_description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis parkingu 3'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking4_coords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Współrzędne parkingu 4'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking4_description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis parkingu 4'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking5_coords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Współrzędne parkingu 5'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking5_description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis parkingu 5'),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(max_length=100, verbose_name='Miejscowość'),
        ),
    ]
