# Generated by Django 5.0 on 2025-06-29 13:43

import locations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_entry_coords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Punkt', 'verbose_name_plural': 'Punkty'},
        ),
        migrations.AlterField(
            model_name='location',
            name='entry_coords',
            field=models.CharField(max_length=50, validators=[locations.validators.validate_coordinates], verbose_name='Współrzędne bramy wjazdowej'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loading_coords',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[locations.validators.validate_coordinates], verbose_name='Współrzędne załadunku/rozładunku'),
        ),
        migrations.AlterField(
            model_name='location',
            name='office_coords',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[locations.validators.validate_coordinates], verbose_name='Współrzędne biura'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking1_coords',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[locations.validators.validate_coordinates], verbose_name='Współrzędne parkingu 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking2_coords',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[locations.validators.validate_coordinates], verbose_name='Współrzędne parkingu 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking3_coords',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[locations.validators.validate_coordinates], verbose_name='Współrzędne parkingu 3'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking4_coords',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[locations.validators.validate_coordinates], verbose_name='Współrzędne parkingu 4'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parking5_coords',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[locations.validators.validate_coordinates], verbose_name='Współrzędne parkingu 5'),
        ),
    ]
