# Generated by Django 5.0 on 2025-06-29 13:43

import parkings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='coords',
            field=models.CharField(max_length=100, validators=[parkings.validators.validate_coordinates]),
        ),
    ]
