# Generated by Django 5.0 on 2025-06-29 17:36

import parkings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_alter_parking_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='coords',
            field=models.CharField(max_length=100, validators=[parkings.validators.validate_coordinates], verbose_name='Współrzędne'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwa'),
        ),
    ]
